spring:
  data:
    mongodb:
      uri: mongodb://eventhub:eventhub_password@localhost:27017/eventhub_auth_db?authSource=admin
  mongodb:
    uri: mongodb://eventhub:eventhub_password@localhost:27017/eventhub_auth_db?authSource=admin