server:
  port: 8082

spring:
  application:
    name: auth-service
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000 # 24 Horas

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "b3,w3c"
    export:
      zipkin:
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"